packages/serverless-deploy-iam/bin/app.ts
Got a recent error in a pipeline. It looks like serverless might require the `lambda:ListTags` permission now. 
`DO-1323: Code Review`
=> Add ListTags permission

packages/static-hosting/lib/static-hosting.ts
Introduced a parameter call `stackExportPrefix` and enable export name in CloudFormation output.
=> DO-1285: Added the Export names for cfnOutput

packages/static-hosting/lib/static-hosting.ts
There are some cases, where we might need to pass additional props rather than defaults for S3 bucket.
For instance,  we might need to pass a Life Cycle Rule for bucket Objects. 
This PR intended to accommodate such a scenario.
=> DO-1285: S3 Extended props

packages/prerender-proxy-internal/lib/handlers/tsconfig.json
To resolve this error:
Error: lib/error-response-construct.ts(22,27): error TS2304: Cannot find name '__dirname'.
=> added node type

packages/basic-auth/.npmignore, packages/cloudfront-security-headers/.npmignore, packages/geoip-redirect/.npmignore, packages/prerender-proxy-internal/.npmignore, packages/prerender-proxy/.npmignore, packages/rabbitmq/.npmignore, packages/static-hosting/.npmignore, packages/waf/.npmignore
Not sure exactly what changed here as the old configuration worked fine here: https://github.com/aligent/cdk-prerender-proxy/blob/main/.npmignore
Tested this locally and it includes the required `js` files that the package was missing.
Without this the included files were:
Which would then cause this error when using the published package:
Theoretically, when we publish to npm now these `js` files will be included and we won't run into this error anymore.
I think the reason this happens is because we exclude handlers in the package.json: `"lib/handlers/**"` but we allow ts files in the .npmignore `!lib/handlers/*.ts`.
=> Add js files to non-ignore list for npm

packages/prerender-fargate/README.md, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/prerender/server.js
This is part of the process to combine the prerender proxy functions into one. 
This replaces the previous basic auth method with a token method. This brings it inline with what prerender.io uses.
=> DO-1360: Change prerender fargate to use a token

packages/prerender-proxy/package.json
Private needs to be disabled to publish a public npm package. Thought I already disabled this but apparently not :man_shrugging:
=> Remove package private option

packages/basic-auth/.npmignore, packages/cloudfront-security-headers/.npmignore, packages/geoip-redirect/.npmignore, packages/rabbitmq/.npmignore, packages/static-hosting/.npmignore, packages/waf/.npmignore
To fix not including `.js` files when publishing the npm packages.
This fix has been already committed to the main branch :)
=> DO-1285: cherry pick a hotfix for npm publish

packages/prerender-fargate/lib/prerender-fargate.ts
Allow a vpc id to be optionally passed. In the event one is not provided, use the default vpc.
=> DO-1363: Resolve default vpc

packages/static-hosting/lib/static-hosting.ts
This value was being used to created SSM values. SSM only supports `._-` as special characters so others will need to be filtered out.
=> Remove special characters from path

package-lock.json, packages/waf/lib/waf.ts, packages/waf/package.json
A client is looking to add the WAF to their Cloudfront distribution so I have made some small refactors to make this a little easier in the upstream repo. The main changes are just making a few more props optional and allowing a list of associations to be provided. 
This is a breaking change so there will need to be a major version bump.
=> Updated WAF Construct

packages/static-hosting/lib/static-hosting.ts, packages/waf/lib/waf.ts
This PR adds support for the WAF to be used with our Cloudfront distribution so we can lockdown via IP, add AWS WAF rules etc.
Changes:
Added support to the WAF Construct to allow both REGIONAL and CLOUDFRONT scopes
Added support to the static hosting construct to import a Web ACL
=> Cloudfront WAF Support

package-lock.json, packages/static-hosting/README.md, packages/static-hosting/lib/static-hosting.ts, packages/static-hosting/package.json
This feature enable us to create and attach response header policies to specified path. 
This is an optional configuration.
1. Create a policy
```sh
// Creating a custom response headers policy -- all parameters optional
const reportUriPolicy = new ResponseHeadersPolicy(this, 'ReportUriPolicy', {
responseHeadersPolicyName: 'ReportUriPolicy',
comment: 'To enable CSP Reporting',
customHeadersBehavior: {
customHeaders: [
{ 
header: 'content-security-policy-report-only', 
value: `default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://some-report-uri-domain.report-uri.com/r/t/csp/wizard`, 
override: true 
},
],
},
});
```
2. Attached policy to desired cache behavior or path
```sh
const responseHeaders: ResponseHeaderMappings[] = [{
header: reportUriPolicy, …
```
=> Static hosting custom header policies

packages/prerender-fargate/.npmignore, packages/prerender-proxy/.npmignore
JS files weren't being included in the npm package. This happened previously and the solution was to explicitly allow `js` files in the package.
This should hopefully fix the import package issues that @crispy101 and I were experiencing.
=> Add explicit allow js files to npmignore

packages/lambda-at-edge-handlers/lib/prerender-check.ts
This is to let Origin request function to know that if the request is coming from a bot, as whitelisting `user-agent` header could cause to have many possible values, and caching based on their values would cause CloudFront to forward significantly more requests to the origin.
=> JBH-615: Set is a bot header

packages/prerender-proxy/lib/handlers/prerender-check.ts
This is to let Origin request function to know that if the request is coming from a bot, as whitelisting user-agent header could cause to have many possible values, and caching based on their values would cause CloudFront to forward significantly more requests to the origin.
=> JBH-615: Set is a bot header in prerender proxy repo

packages/prerender-fargate/lib/prerender/server.js
By processing authentication first, we fix the issue where the s3cache would kick off first on `/`. This would result in showing the contents of the S3 bucket rather than a 401.
=> fix: process authentication first

packages/prerender-proxy/lib/handlers/prerender-check.ts
We have introduced following header to address some concerns with GeoIP redirect logic. 
As we are no longer required this header we shall remove it. 
**Further note:**
This header was used to check if a request coming from a crawler, and if it does, it should NOT redirect based on the GeoIP logic. Instead of using this header, we found that we could leverage,    
-  `x-prerender`
- `x-request-prerender`
headers to see it is a crawler.
=> Prerender check function code cleanup

.gitignore, README.md, package-lock.json, package.json, packages/basic-auth/lib/basic-auth-construct.ts, packages/cloudfront-security-headers/lib/index.ts, packages/geoip-redirect/lib/redirect-construct.ts, packages/graphql-mesh-server/.npmignore, packages/graphql-mesh-server/README.md, packages/graphql-mesh-server/index.ts, packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/pipeline.ts, packages/graphql-mesh-server/lib/redis-construct.ts, packages/graphql-mesh-server/lib/web-application-firewall.ts, packages/graphql-mesh-server/package.json, packages/graphql-mesh-server/tsconfig.json, packages/prerender-proxy/lib/error-response-construct.ts, packages/prerender-proxy/lib/prerender-check-construct.ts, packages/prerender-proxy/lib/prerender-construct.ts
* Adds graphql-mesh-hosting construct
=> MICRO-150: Graphql mesh server

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/redis-construct.ts
Update connection strings to use tokens for attribute references as they are evaluating to null when using the toString() method.
Before:
After:
* 
=> Use tokens for Attribute references

packages/graphql-mesh-server/lib/fargate.ts
* Adds a role to allow users from a different account to assume a role that grants access to view ECS and relevant log information. 
=> Add read only user to access ecs

.gitignore, README.md, package-lock.json, packages/graphql-mesh-server/.npmignore, packages/graphql-mesh-server/README.md, packages/graphql-mesh-server/assets/buildspec.yml, packages/graphql-mesh-server/index.ts, packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/pipeline.ts, packages/graphql-mesh-server/lib/redis-construct.ts, packages/graphql-mesh-server/lib/web-application-firewall.ts, packages/graphql-mesh-server/package.json, packages/graphql-mesh-server/tsconfig.json
------
This PR ports the changes across to the epic from the DO-1285 branch. 
=> Port Graphql Mesh changes from DO branch

packages/prerender-fargate/index.ts, packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/recaching/prerender-tokens.ts
------
*  Use the task role instead of the access key pair to access the s3 bucket
* Export  `PrerenderTokenUrlAssociationOptions`
* N/A
* N/A
=> DO-1554: Replace AWS Access Key Pair with Task Role

.github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, packages/static-hosting/lib/static-hosting.ts
------
* We shall introduce  `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` files to our open-source repos
* Fixed a tiny formatting issue in the static hosting construct which was breaking the build
* N/A
* M/A
⚠️ Please make sure the changes adhere to the guidelines mentioned [here](https://github.com/aligent/cdk-constructs/blob/feature/DO-1486_contributing_guidelines/CONTRIBUTING.md)
🛈  When you've finished leaving feedback, please add a final comment to the PR tagging the author, and letting them know that you have finished leaving feedback
=> DO-1486: Include CODE_OF_CONDUCT.md and CONTRIBUTING.md files

packages/prerender-fargate/lib/prerender/server.js
------
* Send 'X-Prerender' HTTP header along with the prerender requests
* N/A
* N/A
=> DO-1557: Send 'X-Prerender' HTTP header along with the prerender requests

packages/static-hosting/lib/static-hosting.ts
* The `distribution` property was not assigned when importing changes
=> TF-1072: Assign distribution as class property

packages/prerender-fargate/index.ts, packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts
------
* Let the local stack configure scaling configurations
* This will allow more control over the prerender cluster performace
* N/A
* N/A
=>  Make the scaling options configurable

packages/prerender-fargate/index.ts, packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/recaching/prerender-recache-api-construct.ts
------
* Make the re-caching concurrency configurable
* N/A
* N/A
=> Make the re-caching concurrency configurable

packages/prerender-fargate/README.md, packages/prerender-fargate/lib/prerender-fargate-options.ts
------
* Prerender Fargate Readme update
* N/A
* N/A
=> DO-1545: Prerender Fargate Readme update

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Allow passing of custom cpu scaling intervals. 
=> feat: add custom cpu scaling to mesh

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Add default rate limiting rule
* Allow passing of custom WAF rules
=> feat: Graphql Mesh add WAF rules

packages/prerender-fargate/lib/recaching/prerender-tokens.ts
* Use NestedStack for the SSM Param creation to get it automatically created under the condition specified.
* 
* 
=> fix bug not firing nested stack for ssm paramter creation

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Add support to block ipv6 addresses
=> feat: add ipv6 support for block list

packages/graphql-mesh-server/lib/dashboard.ts, packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/metrics.ts
Bit of a big one :sweat_smile: All changes are around monitoring of the graphql server. Now by default there are:
- Common alarms (that can optionally notify on an SNS topic)
- A dashboard
Currently no way to customise these alarms but I am worried about the props getting too large. Keen to hear your thoughts on this!
=> Graphql server monitoring enhancements

packages/basic-auth/lib/basic-auth-construct.ts, packages/cloudfront-security-headers/lib/index.ts, packages/geoip-redirect/lib/redirect-construct.ts, packages/prerender-proxy/lib/error-response-construct.ts, packages/prerender-proxy/lib/prerender-cf-cache-control-construct.ts, packages/prerender-proxy/lib/prerender-check-construct.ts, packages/prerender-proxy/lib/prerender-construct.ts
Fix the imports of experimental cloudfront edge functions.
Ref: https://github.com/aws/aws-cdk/issues/18163#issuecomment-1002714184
Error:
```
npx cdk synth 'Staging/*' 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './aws-cloudfront/lib/experimental' is not defined by "exports" in node_modules/aws-cdk-lib/package.json
at new NodeError (node:internal/errors:405:5)
at exportsNotFound (node:internal/modules/esm/resolve:362:10)
at packageExportsResolve (node:internal/modules/esm/resolve:698:9)
at resolveExports (node:internal/modules/cjs/loader:567:36)
at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
at …
```
=> Fix imports of experimental cloudfront lambda@edge functions

packages/graphql-mesh-server/assets/handlers/notify-sns.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/pipeline.ts
Allow the region to be configured via props (default to the region the stack is deployed in), so that the lambda can use the destination region when the stack is deployed in another region.
e.g. when deployed the SNS topic exists in AP-SOUTHEAST-2 and the lambda is deployed in US-EAST-1 the client should be configured to use AP-SOUTHEAST-2. 
=> Make region in AWS Lambda configurable for cross-region notifications

.eslintrc.json
* We've had quite a few of these warnings in this repo for a while. I've resolved them as part of #1262. By changing eslint to error we should stop these from being re-introduced.
=> chore: change from warn to error

packages/static-hosting/lib/static-hosting.ts
------
This PR allows passing through a request and cache policy so that prerender headers can be added to the allowlist. Otherwise the prerender headers are not passed to the origin request lambda@edge function and the origin switch to prerender is not performed.
=> HOTFIX: Fix Prerender proxy lambda@edge

packages/static-hosting/lib/static-hosting.ts
* Expose the OriginAccessIdentity so we can modify the permissions in stacks. Required for adding permission to execute a lambda function via url.
=> feat: expose oai

packages/static-hosting/lib/static-hosting.ts
* Adds support to specify the `comment` property of the CloudFront distribution.
*
=> Add distribution comment prop

packages/static-hosting/lib/static-hosting.ts
* Get rid of SSL/TLS ciphers that do not offer forward secrecy (FS) also known as perfect forward secrecy (PFS). 
It's a feature that provides assurances the session keys will not be compromised even if server's private key is compromised.
* 
* 
=> DO-1608: use most recent cipher suite for CloudFront distribution security policy

packages/graphql-mesh-server/README.md
* Updates the readme props. They were pretty out of date :fearful: 
=> chore: update readme props

packages/prerender-fargate/lib/recaching/prerender-recache-api-construct.api.ts, packages/prerender-fargate/lib/recaching/prerender-recache-api-construct.consumer.ts
* Use `for` instead of `forEach` in order to ensure each of the URLs are requested before the lambda funtion completes its execution
* Add more meaningful logs
* 
* 
=> Fix/DO-1610: address prematured completion of recache requests

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Adds an option to block all requests. This can be used in conjunction with allow list to have a whitelist of IPs that can access the mesh
* Convert rate limit bypass to a generic IP allow list
=> Add allow list and option to block all requests

packages/lambda-at-edge-handlers/lib/prerender-check.ts, packages/prerender-proxy/lib/handlers/prerender-check.ts
------
* DO-1621: Prerender Proxy - Mark Schema user agent as a bot
* 
* 
* Note that this is a must if you are using the GeoIP redirect function, as only Bots are excluded from the logic.
* We might need to bring the same change to CDK V2
=> DO-1621: Prerender Proxy - Mark Schema user agent as a bot

package-lock.json, packages/graphql-mesh-server/assets/handlers/invalidate-cloudfront-cache.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/pipeline.ts, packages/graphql-mesh-server/package.json
* Adds an optional lambda function that invalidates the `/graphql` endpoint on a successful mesh deployment 
=> feat: add lambda to pipe to invalidate cache

packages/static-hosting/lib/arbitrary-path-remap.ts
Update to use Node 16 for the path remap so older stacks can still be deployed.
This will be an issue again on Jul 15, 2024 as node 16 functions will be blocked from being created then. But any updates to higher node versions would require an update to CDK V2
=> Hotfix: Update node version

packages/prerender-fargate/lib/prerender/server.js, packages/prerender-fargate/package.json
* Rolling back the change made in [7f8175a](https://github.com/aligent/cdk-constructs/pull/1273/commits/7f8175a89c9b0bec27da6dd8c05484f0f0e63b44) to stop the app from fetching origin after checking the cached object. This caused unnecessarily high response time.
* 
* 
=> DO-1394: return cached object when found, without proceeding to fetch origin

packages/prerender-fargate/lib/recaching/prerender-recache-api-construct.ts
* Recaching one URL usually takes ~ 10 seconds. The maximum number of URLs in one recaching request chunk is 10, so 60 seconds was not enough to finish them up before the timeout. This change provides ample time for the lambda to finish the recaching.  
* 
* 
=> Provide enough time to handle ten URLs in a chunk

packages/graphql-mesh-server/assets/handlers/maintenance/lib/file.ts, packages/graphql-mesh-server/assets/handlers/maintenance/maintenance.ts, packages/graphql-mesh-server/assets/handlers/maintenance/whitelist.ts, packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/maintenance.ts
* Adds maintenance mode logic to the mesh. 
* Includes an API GW interface to control whitelist and toggling the maintenance mode.
* Works alongside our custom maintenance mode plugin to detect when the maintenance mode file is there and enable maintenance mode when it's detected
* Review https://github.com/aligent/cdk-constructs/pull/1337 first :pray: 
=> feat: maintenance mode

packages/prerender-fargate/lib/prerender/server.js, packages/prerender-fargate/package.json
… to allow the custom x-prerender req header to go through
* the custom _x-prerender_ req header was causing "timed out" error as it is not in the Access-Control-Allow-Headers response header.
* suppressing this security check on headless chrome to ignore the CORS header.
* release 2.3.3
* 
* 
=> DO-1557: disable checking CORS

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Adds support for a custom WAF name. This was already supported from the WAF construct but we weren't passing a prop all the way down. 
=> feat: support custom waf name for mesh

package-lock.json, packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/maintenance.ts, packages/graphql-mesh-server/lib/pipeline.ts
* Adds optional names to ECS cluster, service and repository, looks more readable in the AWS console
* Removes the any IP4v security group rule in favour for service's security group (the other option is to allow VPC CIDR block if other things in the VPC needs access)
=> Add optional props for construct name

packages/graphql-mesh-server/lib/pipeline.ts
* Adds tag permissions to ECS deployment pipeline. This way when the pipe triggers a deployment to ECS, if the task requires a tag it has permission to add it.
=> feat: add ecs tag permission to pipe

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* :facepalm: I forgot to use `serviceName` prop in the actual construct
* All the props added needed to be actually available at the top level construct so they can be passed down #1353
=> chore: Add props to top level construct

packages/static-hosting/lib/static-hosting.ts, packages/static-hosting/package.json
* Let custom behaviors listed first before static file extension mapping to avoid any file requests in the custom behavior from getting caught by the preceeding static mappings
* 
* 
=> reorder custom behaviors to be evaluated before other static mappings

packages/prerender-proxy/lib/handlers/cache-control.ts, packages/prerender-proxy/package.json
* Overwrite cache-control header set by the Origin, by updating the case to match the original one
* 
* 
=> [Legacy] let prerender response override cache-control header set, by matching the case

.github/dependabot.yml, package-lock.json, packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/recaching/prerender-recache-api-construct.ts
* Removed dependabot
* Add optional name props
=> DO-1652: Add name props, remove dependabot

packages/static-hosting/lib/static-hosting.ts
* Ignore wildcards at the end of from when routing from CDN to the BE. 
=> fix: ignore ending wildcards

packages/static-hosting/lib/static-hosting.ts
* Ignore wildcards at the end of from when routing from CDN to the BE. (Required for legacy project but have included here for CDK 2: https://github.com/aligent/cdk-constructs/pull/1371)
=> fix: ignore wildcards at end of path

packages/basic-auth/lib/basic-auth-construct.ts, packages/cloudfront-security-headers/lib/index.ts, packages/prerender-proxy/lib/error-response-construct.ts, packages/prerender-proxy/lib/prerender-cf-cache-control-construct.ts, packages/prerender-proxy/lib/prerender-check-construct.ts, packages/prerender-proxy/lib/prerender-construct.ts, packages/static-hosting/lib/arbitrary-path-remap.ts
* Upgrade all instances of Node 14 to Node 16. The highest version of Node on CDK 1 is Node 16 so we should be upgrading existing infras to use CDK 2 where possible. 
=> chore: upgrade legacy lambda to use node 16

package-lock.json, packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Added a new prop for passing secrets via secrets manager. The ECS task execution will pass the secret value as a JSON object when launching the task.
Example:
=> DO-1631: Use secrets manager for passing secrets

packages/prerender-proxy/lib/handlers/prerender-check.ts, packages/prerender-proxy/lib/prerender-check-construct.ts, packages/prerender-proxy/lib/prerender-construct.ts, packages/prerender-proxy/lib/prerender-lambda-construct.ts
* Update the list of bots
* Allow passing a custom regex string for custom bot detection  
=> feat: support custom bot detection string

package-lock.json, packages/prerender-fargate/.gitignore, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/prerender/Dockerfile, packages/prerender-fargate/lib/prerender/package.json, packages/prerender-fargate/lib/prerender/server.js, packages/prerender-fargate/lib/prerender/utils/logger.js
* Add structured logging for prerender. This allows us to store the logs, parse and have visibility on access.
**Screenshots (if applicable)**
=> Prerender structured logging

packages/static-hosting/lib/static-hosting.ts
Response page paths must begin with a slash. We changed the default to remove the slash which causes errors on deploy. 
=> fix: revert error response path

packages/prerender-fargate/lib/monitoring.ts, packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/recaching/prerender-recache-api-construct.ts
* Adds a dashboard to help monitor the Prerender construct
* Adds functionality for alerts (although only one is configured at this stage)
It's difficult to review dashboard code so I've attached images of what the deployed dashboard looks like. Note that these screenshots were taken on staging where data is minimal but hopefully it gives a rough idea of what it'll look like.
**Screenshots**  
=> feat: add cloudwatch dashboard to Prerender construct 

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts, packages/graphql-mesh-server/lib/metrics.ts
Update the mesh construct so that it can be deployed multiple times to the same account with the same defaults. Currently if you deploy it more than once it will fail and rollback due to creating a dashboard and dynamo DB table with the same name in both stacks. This PR removes the default dynamo DB table and updates the dashboard to include the stack name so it will not conflict.
=> Hotfix: Allow multiple stacks

packages/waf/lib/waf.ts, packages/waf/package.json
* introduce CloudWatch logging to WAF, keeping default as true. 
* 
* 
* log group name needs to be "aws-waf-logs-xxxxx" in order to be associated to a WebACL.
=> introduce logging to WAF, bumping up to 2.2.0

packages/graphql-mesh-server/assets/nginx/Dockerfile, packages/graphql-mesh-server/assets/nginx/nginx.conf, packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/maintenance.ts
* The mesh is currently missing access logs. The application layer logs are often unreliable too. By adding an nginx container that sits in front of the mesh we can ensure we are capturing access level logs.
* We want to ensure this works as an in place upgrade for existing stacks. By passing a custom task definition we can still use the same load balancer and therefore upgrade without changing DNS records.'
* My nginx config skills are not the best so please let me know if anything needs changing there :pray: 
=> DO-1704: add nginx to the mesh

packages/graphql-mesh-server/lib/pipeline.ts
* When nginx is in use, this becomes the default container. However when the mesh deploys we want to target the mesh container. This removes the assumption that the mesh is the default container and instead searches for it.
=> fix: specifically target mesh container for deploy

packages/static-hosting/lib/static-hosting.ts
* Adds the option to pass custom behaviour overrides to remap behaviours. 
* This is useful for many reasons, one of which is when you need to customise the cache policy
=> Static hosting behaviour remap options

packages/graphql-mesh-server/lib/fargate.ts
* Changes the default scaling rule for the mesh. These recommended defaults were based on load testing however I'm open to some discussion here.
* Provides a better interface to override scaling
=> feat AM-1945: modify mesh scaling rules

packages/esbuild/esbuild.ts
* Adjusted the logic of the esbuild behaviour options so that if more than just `define` and `entryPoints` are declared the other values will be used. (such as `minify`)
* Didn't allow overriding of `minifyIdentifiers` as it causes errors
=> Change esbuild logic to allow passing thru of custom configuration

packages/static-hosting/lib/static-hosting.ts
Despite the AWS docs saying this value is quote: "Maximum HTTP version to support". This is a lie :-1: 
What it *actually* means is what the HTTP version should be with a fallback to version 1.1. If you want HTTP3 to fallback to HTTP2 you must explicitly define that. 
I can't think of a situation where we'd only want HTTP3 but not HTTP2 so I think this is a reasonable default.
=> fix: add support for http2

packages/prerender-proxy/lib/prerender-lambda-construct.ts, packages/static-hosting/index.ts, packages/static-hosting/lib/static-hosting.ts
- Added an `id` tag to prerender function names to avoid duplicate named function issues
- Export remap path from construct for easier uniformity with types
- `behaviourPrefixes` to allow for behaviours on regional prefixes such as `au/` or `nz/`
- These changes allow for the CDK v2 upgrade to work for multiple brands, impact on other clients untested but it is all conditional so shouldn't affect them
=> Behaviour Prefixes (for CDK v2 upgrade)

packages/prerender-fargate/lib/prerender/Dockerfile
* Upgrades the Prerender node image to node 22
* This in turn also upgrades to version of Chrome from 119 to 131
=> chore: upgrade prerender to node 22

packages/prerender-fargate/lib/prerender/server.js
* A change to prerender's logic when it comes to adding a correct leading slash onto the location returned in 301 redirect responses. This affected some prerender instances and led to redirected URLs having doubly-appended responses for example: `https://example.com/trains/steam-engines/trains/steam-engines` rather than the correct response  `https://example.com/trains/steam-engines`
* Changed the logic to be a little more clear
🛈  When you've finished leaving feedback, please add a final comment to the PR tagging the author, letting them know that you have …
=> Prerender Fargate Leading Slash Logic

.github/workflows/release.yml
* Enable corepack in the release pipeline so yarn berry can be installed
=> fix: enable corepack during release

.github/dependabot.yml
To automate dependency version updates while ensuring that the pull requests (PRs) generated are meaningful and actionable, rather than creating unnecessary noise. This is to maintain secure and up-to-date dependencies in our codebase efficiently.
**Configuration Highlights**
1. Automatic version updates
- Dependabot will automatically generate pull requests for dependency updates weekly.
- Major version updates are   to avoid breaking changes; only minor updates and patches are allowed. For major upgrades, manual configuration changes will be required.
2. Target Branch
- All PRs are initially directed to the dependabot-test branch for evaluation.
- Once the configuration is validated and deemed appropriate, the target branch will be switched to …
=> DO-1881 Enable Dependabot Automatic version updates

packages/esbuild/README.md
Added initial README for esbuild, backwards engineering the definitions from the code. README includes:
- A description including the purpose of this construct
- Package name
- Package version (using badges)
- Example code
- Links to esbuild API manual
**Notes to reviewers**
=> Added README for esbuild package

packages/static-hosting/README.md
README updated with:
- Package versions (using badges)
- Options
**Screenshots (if applicable)**   
**Notes to reviewers**
=> Updated README for static-hosting package

.github/workflows/build.yml
A GitHub Actions workflow step contains a template expression referencing potentially untrusted GitHub context fields. This may allow malicious input to be injected into shell commands, leading to a potential supply chain attack as tokens of the CI/CD pipeline could be exfiltrated.
The env block ensures GitHub Actions resolves the expression safely before passing it to the shell. This should avoid the above issue.
=> chore: fix template injection vulnerability

packages/header-change-detection/project.json, packages/header-change-detection/tsconfig.app.json
------
Build is currently failing with the below as the lambda code is being transpiled as part of the publishing step. This change will force the typescript file to be included in the final artifact so it can be built during the cdk synth step.
```
[ERROR] Could not resolve "node_modules/@aligent/cdk-header-change-detection/lib/lambda/header-check.ts"
```
=> HOTFIX: Ensure lambda code is not built and bundled

packages/header-change-detection/README.md, packages/header-change-detection/lib/header-change-detection.ts, packages/header-change-detection/lib/lambda/header-check.ts
------
- Update Aligent's Header Change Detection to accommodate BigCommerce checkout behavior
- Added props to have an ability to add custom HTTP statuses.
- Joined the URL Array to a single string before saving.
Before the change
After the Change 
Test with added 406 status
Test without the 406
* 
=> Feature/DO-1834 Header Change Detection add HTTP status flags for custom behaviour for BigCommerce

.gitignore, packages/geoip-redirect/README.md, packages/geoip-redirect/index.ts, packages/geoip-redirect/lib/handlers/redirect.ts, packages/geoip-redirect/lib/redirect-construct.ts
* Created a new interface `RedirectFunctionOptions` to provide a better way to pass region codes and domains to redirect to.
* Changed the functional logic to allow for more than just path rewrites such as `.com/au`. You can now redirect directly to a site or to a path based rewrite.
* Added a README
=> GeoIP | Modular Region Domains and Rewrite Paths

packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts
* Allow easily overriding the `targetUtilizationPercent` value
* Change the default to much lower to actually scale with load. Prerender CPU load is quite bursty so an average CPU of 10% means it's under quite a bit of load. The max average I've seen is only 25% so the previously set 50% would never trigger.
=> feat DO-1856: add option for CPU scaling

packages/geoip-redirect/README.md, packages/header-change-detection/README.md, packages/header-change-detection/lib/header-change-detection.ts
* removed `set-cookie` header from the monitoring so that it's less annoying (it's not a security header so not needed to monitor as per PCI standards)
* also updated the GeoIP readme as a small fix to due to changing the logic and forgot to change readme
=> Removed set-cookie header, updated README

packages/static-hosting/lib/static-hosting.ts
* include cspObject property to specify CSP file
=> DO-1852: include cspObject property to specify CSP file

packages/graphql-mesh-server/README.md, packages/graphql-mesh-server/assets/handlers/maintenance/lib/file.ts, packages/graphql-mesh-server/assets/handlers/maintenance/maintenance.test.ts, packages/graphql-mesh-server/assets/handlers/maintenance/maintenance.ts, packages/graphql-mesh-server/assets/handlers/maintenance/whitelist.test.ts, packages/graphql-mesh-server/assets/handlers/maintenance/whitelist.ts, packages/graphql-mesh-server/jest.config.ts, packages/graphql-mesh-server/jest.mock-env.ts, packages/graphql-mesh-server/lib/maintenance.ts
------
This PR updates the whitelist API, maintenance mode API and maintenance file to use JSON so that the API and mesh can support having individual sites in / out of maintenance mode without affecting the others.
I considered using multiple files with a "website scope code" e.g. `maintenance.au.enabled` but I think that will get a bit difficult to use as site counts grow. 
🛈  When you've finished leaving feedback, please add a final comment to the PR tagging the author, letting them know that you have finished …
=> Add multi site support

packages/header-change-detection/lib/header-change-detection.ts
* Lamdba could time out especially when checking multiple domains. Making it configurable, with the default being 10 seconds, long enough to perform multiple checks. (AWS-default is 3 seconds)
* 
* 
=> Make Lambda timeout configurable, with 10 sec by default

.github/dependabot.yml
* Make dependabot target main
* The PRs dependabot is making seem pretty good, happy to test by merging some in
* I've tested the a couple of the branches and they seem be working with builds
=> chore: set dependabot to target main

.github/workflows/changeset-check.yml, .github/workflows/changeset-release.yml, .github/workflows/pull-request.yml, .github/workflows/update-lockfile.yml, yarn.lock
This PR fixes lockfile issues in our CI/CD workflows by:
1. Adding frozen lockfile checks to pull requests
2. Updating the lockfile during releases when changesets modifies package versions
3. Fixing changeset package detection to avoid false positives from nx
When changesets updates package.json files during the release process, the yarn.lock file becomes out of sync. This causes subsequent `yarn install --frozen-lockfile` commands to fail because the lockfile doesn't match the updated package.json files.
Additionally, nx was incorrectly marking all packages as "affected" whenever yarn.lock changed, causing unnecessary CI runs and changeset checks even when no actual package code changed.
This issue is documented in the changesets repository: …
=> DO-1284: Fix changeset release workflow lockfile issue

.github/workflows/changeset-release.yml, yarn.lock
- Fix changeset release workflow failing due to lockfile modification restrictions
- Update lockfile after package versioning but before committing
- Ensures release PRs include updated yarn.lock with correct interdependency versions
The release process was failing with error:
```
YN0028: The lockfile would have been modified by this install, which is explicitly forbidden.
```
This occurred because:
1. During changeset publish, package interdependencies are updated (e.g., `@aligent/cdk-esbuild` from `^2.5.0` to `^2.5.1`)
2. These updates require lockfile changes but weren't being committed to the release PR
3. The workflow tried to install with outdated lockfile entries
- Add `version: yarn changeset:version && yarn install` to update lockfile after versioning
- This ensures release PRs …
=> DO-1802: Fix changeset release workflow lockfile updates
