aligent/cdk-constructs

packages/prerender-proxy-internal/tsconfig.json
Update project_root/tsconfig.json
=> added node type

packages/prerender-proxy/index.ts
export `CloudFrontCacheControlOptions`  to enhance the usage experience
=> Export CloudFrontCacheControlOptions

packages/static-hosting/lib/static-hosting.ts
By default static files should be mapped to the S3 bucket. 
In a situation where this is not desired, there is an optional parameter to disable the behaviour.
=> DO-1362: Map static files to S3 origin by default

packages/static-hosting/package.json
Update main in the package.json. this should fix, `SyntaxError: Cannot use import statement outside a module` issue.
=> Update the main file in package.json

package-lock.json, packages/static-hosting/lib/static-hosting.ts
This PR is CDK V1 version of #290 
> Introduced a parameter call stackExportPrefix and enable export name in CloudFormation output.
=> Include cdk exports

package-lock.json, packages/static-hosting/lib/static-hosting.ts
This PR is CDK V1 version of #311
> There are some cases, where we might need to pass additional props rather than defaults for S3 bucket.
For instance, we might need to pass a Life Cycle Rule for bucket Objects.
This PR intended to accommodate such a scenario.
=> Static Hosting: S3 Extended props

README.md, package-lock.json, packages/shared-vpc/.gitignore, packages/shared-vpc/.npmignore, packages/shared-vpc/README.md, packages/shared-vpc/index.ts, packages/shared-vpc/lib/shared-vpc.ts, packages/shared-vpc/package.json, packages/shared-vpc/tsconfig.json
Takes https://bitbucket.org/aligent/aligent-shared-vpc-stack/ and turns it into a CDK construct.
=> Add Shared VPC construct

packages/shared-vpc/.npmignore, packages/shared-vpc/package.json
RE: https://github.com/aligent/cdk-constructs/pull/367
=> Update .npmignore to allow .js files

packages/static-hosting/lib/static-hosting.ts
=> Add gif to file mapping list as per new PWA requirement

packages/lambda-at-edge-handlers/lib/prerender-check.ts
Reverts aligent/cdk-constructs#1040
Reverting the PR as this could be achieved using `x-prerender`, `x-request-prerender`
=> Revert "JBH-615: Set is a bot header"

packages/lambda-at-edge-handlers/lib/prerender-check.ts, packages/prerender-proxy/lib/handlers/prerender-check.ts
Google has recently added a new crawler to its list called ‘Google-InspectionTool’
Its used for search testing tools like Rich Result Test and URL inspection in search console, it also mimics Googlebot
- Google-InspectionTool
- Googlebot
Full user agent string:
MobileMozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; Google-InspectionTool/1.0)
DesktopMozilla/5.0 (compatible; Google-InspectionTool/1.0)
More info about this specific crawler can be found [here]( https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#google-inspectiontool)
=> Include Google-InspectionTool in prerender check function

.github/pull_request_template.md, package.json, packages/basic-auth/lib/handlers/basic-auth.ts, packages/cloudfront-security-headers/lib/index.ts, packages/geoip-redirect/lib/handlers/redirect.ts, packages/lambda-at-edge-handlers/lib/prerender-check.ts, packages/prerender-proxy/lib/handlers/prerender-check.ts, packages/static-hosting/lib/handlers/remap.ts, packages/static-hosting/lib/static-hosting.ts
------
* Fix linting errors
* N/A
* N/A
⚠️  Please make sure the changes are adhere to the guidelines mention [here](https://aligent.atlassian.net/wiki/spaces/AL/pages/2758836297/Development+checklist+FE+BE+INT)
* Next we might need to add checks to the GitHub action
=> Fix linting issues

.github/pull_request_template.md, .github/workflows/build.yml, package.json
------
* Include Linting and Formatting checks in PR builds
* 
* As we are not directly committing to the main branch, rather than using a PR, the checks on the release pipeline has been excluded. 
⚠️  Please make sure the changes are adhere to the guidelines mention [here](https://aligent.atlassian.net/wiki/spaces/AL/pages/2758836297/Development+checklist+FE+BE+INT)
*
=>  Include Linting and Formatting checks in PR builds

packages/static-hosting/lib/static-hosting.ts
* Adds text file formats to the list of static files
=> feat: add text files

package-lock.json, packages/static-hosting/lib/static-hosting.ts, packages/waf/README.md, packages/waf/lib/waf.ts
=> enable ipv6 ipset

packages/prerender-proxy/lib/handlers/prerender.ts
=> give higher timeout for prerender to talk to the backend

packages/static-hosting/lib/static-hosting.ts
------
* Add distribution and bucket as read only class properties so that they can be referenced by other resources 
=> Add class properties

packages/prerender-fargate/lib/prerender/server.js
=> add missing module

packages/prerender-proxy/index.ts, packages/prerender-proxy/lib/handlers/prerender.ts
------
* Expose prerender props so we can type check before passing them to the local stack
* Fixed a typo in the prerender lib function
* N/A
* N/A
=> DO-1495: expose prerender proxy props for individiual construct

packages/prerender-fargate/index.ts, packages/prerender-fargate/lib/prerender-fargate.ts
------
* Using .toString() on Secrets seems no longer accepted without calling `.unsafeUnwrap()` first.
* Export prerender Fargate option interface
* N/A
* 
🛈  When you've finished leaving feedback, please add a final comment to the PR tagging the author, and letting them know that you have finished leaving feedback
=> DO-1543: call unsafeUnwrap to pass the secret key to the env

package-lock.json, packages/basic-auth/lib/basic-auth-construct.ts, packages/basic-auth/package.json, packages/cloudfront-security-headers/lib/index.ts, packages/cloudfront-security-headers/package.json, packages/geoip-redirect/lib/redirect-construct.ts, packages/geoip-redirect/package.json, packages/prerender-proxy/lib/error-response-construct.ts, packages/prerender-proxy/lib/prerender-cf-cache-control-construct.ts, packages/prerender-proxy/lib/prerender-check-construct.ts, packages/prerender-proxy/lib/prerender-construct.ts, packages/prerender-proxy/package.json, packages/static-hosting/lib/path-remap.ts, packages/static-hosting/package.json
* Update package name to have `cdk-` prefix so it can be published and used downstream.
=> TF-1072: Update esbuild package name

package-lock.json, packages/prerender-fargate/package.json
------
* Remove unwanted deps from prerender fargate construct
* N/A
* N/A
=> DO-1559: remove unwanted deps from prerender fargate construct

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Enable container insights by default
=> feat: enable container insights

packages/esbuild/esbuild.ts, packages/graphql-mesh-server/lib/redis-construct.ts, packages/lambda-at-edge-handlers/lib/error-response.ts, packages/prerender-proxy/lib/handlers/error-response.ts, packages/static-hosting/lib/handlers/remap.ts, packages/static-hosting/lib/static-hosting.ts
* Should resolve all the errors `Unchanged files with check annotations` we keep seeing in PRs
=> chore: resolve linting errors

packages/graphql-mesh-server/lib/metrics.ts, packages/graphql-mesh-server/lib/web-application-firewall.ts
* I must have missed adding these :slightly_frowning_face:. Adds metrics for WAF!
=> feat: fix waf metrics

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Removed required cert. When an undefined value is passed a default cert is generated. 
=> feat: remove required cert

packages/graphql-mesh-server/lib/fargate.ts
* Adds x-ray container to ECS. This will allow the mesh to send analytics to x-ray to allow for easier troubleshooting.
=> feat: add support for AWS X-Ray

packages/graphql-mesh-server/lib/fargate.ts
* Adds a DynamoDB table to store session data.
* This works alongside our custom plugin to create refresh tokens alongside JWTs and use that as a validation to extend sessions.
=> feat: add dynamodb auth table

packages/graphql-mesh-server/.npmignore
* The maintenance handlers weren't included in the final build :disappointed: This fixes that
**Screenshots**  
=> fix: include all handlers in the build

packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/package.json
* introduce _usePrivateSubnets_ flag to locate the service into private subnets
* 
* 
=> allow tasks to use private subnets if specified

packages/prerender-fargate/package.json
Actually lock the version :grimacing:
=> fix: actually lock the version this time

.eslintrc.json
* Not sure why it was ever set to browser :thinking: 
=> fix: set eslint to use node env, not browser

packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/recaching/prerender-recache-api-construct.ts
* Added top level props so that the names can be passed to constructs
=> DO-1652: Add top level props for rest, queue names

packages/prerender-proxy/lib/handlers/prerender-check.ts
* Adds a few extra bots:
* Add AhrefsBot
* Add Semrush bots
* Add Screaming frog default bot
=> feat: add extra bots to prerender detection

packages/graphql-mesh-server/lib/pipeline.ts
Reverts aligent/cdk-constructs#1354
=> Revert "feat: add ecs tag permission to pipe"

packages/prerender-proxy/lib/handlers/prerender-check.ts
* Adds a few extra bots:
* Add AhrefsBot
* Add Semrush bots
* Add Screaming frog default bot
=> feat: add extra bots to prerender

packages/prerender-proxy/lib/handlers/prerender-check.ts, packages/prerender-proxy/lib/prerender-check-construct.ts, packages/prerender-proxy/lib/prerender-lambda-construct.ts
* Update the list of bots
* Allow passing a custom regex string for custom bot detection  
=> feat: custom bot detection (legacy)

packages/prerender-proxy/lib/handlers/prerender-check.ts
* Remove a pipe :open_mouth::anger: 
=> fix: remove extra |

packages/prerender-proxy/lib/handlers/prerender-check.ts
* Include case insensitive flag
=> feat: add case insensitive flag

packages/prerender-fargate/lib/monitoring.ts
* Add a missing single quote :disappointed: 
=> fix: add missing quote

packages/prerender-fargate/lib/prerender-fargate-options.ts, packages/prerender-fargate/lib/prerender-fargate.ts, packages/prerender-fargate/lib/prerender/server.js
* Adds the option to cache 404s in S3
=> feat: cache 404s

packages/graphql-mesh-server/assets/nginx/nginx.conf
* Add X-Forwarded-For header to json logs and
* Remove server version from response headers 
=> Graphql Mesh Logging Updates

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
------
* Add prop to optionally disable ECS exec as required 
=> FEAT: Add prop to disable ECS exec

.github/workflows/release.yml
* Fallback to npm for config set
=> fix: set registry with npm

README.md, packages/basic-auth/README.md
**Root**
- Updated description + table descriptions
- Filled out steps for development, merging, and creating release
**Basic Auth**
- Added overview of package
- Installation and minimal example
- Info for error handling
=> Updated readme for basic auth and root

.github/dependabot.yml
=> Sync dependabot-test branch

packages/cloudfront-security-headers/README.md
Added:
- Extra descriptions
- Package versions
- Usage and default options
- Which security headers are attached
**Notes to reviewers**
=> Updated README for cloudfront-security-headers package

packages/prerender-proxy/package.json, yarn.lock
* Updating axios to address vulnerability found in versions < 1.7.4
=> Updating Axios which is used in prerender-proxy

packages/header-change-detection/package.json, packages/prerender-proxy/package.json, yarn.lock
* Upgrade axios to resolve open CVE (CVE-2025-27152)
=> chore: update axios

.github/workflows/pull-request.yml, README.md
* Update readme table 
* Add a check to confirm the root readme has been updated
=> Update readme table

packages/graphql-mesh-server/lib/fargate.ts, packages/graphql-mesh-server/lib/graphql-mesh-server.ts
* Adds support for allow listing ipv6 addresses
=> feat: support ipv6 allow listing

package.json, packages/basic-auth/package.json, packages/esbuild/package.json, packages/feature-env-handlers/package.json, packages/geoip-redirect/package.json, packages/graphql-mesh-server/package.json, packages/header-change-detection/package.json, packages/prerender-fargate/package.json, packages/prerender-proxy/package.json, packages/rabbitmq/package.json, packages/static-hosting/package.json, packages/waf/package.json
* Update licenses everywhere to MIT.
=> chore: update licenses

.github/workflows/release.yml
* Prevent package release off non-main branches
* 
=> DO-1857: prevent package release off non-main branches

packages/prerender-proxy/lib/handlers/prerender-check.ts
* add AI bots' user-agent strings to pre-rendering list
* 
* 
=> DO-1897: add AI Bots to pre-rendering list
